import type { Area } from "@/content/types";

export const gangnam: Area = {
  slug: "gangnam",
  nameJa: "江南",
  nameKo: "강남",
  reading: "カンナム",
  tagline: "カロスキルは、いま行かなくて大丈夫",
  intro:
    "空き店舗が4割を超えていて、カロスキルは正直さびしい状態。代わりに狎鴎亭ロデオと島山公園のほうへ。今の江南はこっちに移りました。",
  keyColor: "blush",
  station: {
    line: "水仁盆唐線",
    name: "狎鴎亭ロデオ駅",
    exit: "5・6番出口",
  },
  goodFor: [
    "月曜に予定を組みたい人（ほぼ全部開いてます）",
    "ショッピング・K-ビューティー好き",
    "新しいカフェとフラッグシップを効率よく回りたい人",
  ],
  notFor: [
    "「江南」を1つの街だと思っている人（駅・狎鴎亭・三成は徒歩でつながりません）",
    "カロスキルを1番に想像している人（今は空室率43.9%です）",
    "静かな街並みを歩きたい人",
  ],
  weekday: {
    mon: "good",
    tue: "good",
    wed: "good",
    thu: "good",
    fri: "good",
    sat: "good",
    sun: "good",
  },
  weekdayNote: "ほぼ全施設が年中無休。月曜に予定が崩れたときの受け皿",
  weekdayTable: [
    {
      facility: "狎鴎亭ロデオ通り",
      states: {
        mon: "good",
        tue: "good",
        wed: "good",
        thu: "good",
        fri: "good",
        sat: "good",
        sun: "good",
      },
    },
    {
      facility: "ハウス島山",
      states: {
        mon: "good",
        tue: "good",
        wed: "good",
        thu: "good",
        fri: "good",
        sat: "good",
        sun: "good",
      },
    },
    {
      facility: "奉恩寺",
      states: {
        mon: "good",
        tue: "good",
        wed: "good",
        thu: "good",
        fri: "good",
        sat: "good",
        sun: "good",
      },
      note: "5:00-22:00",
    },
    {
      facility: "ピョルマダン図書館",
      states: {
        mon: "good",
        tue: "good",
        wed: "good",
        thu: "good",
        fri: "good",
        sat: "good",
        sun: "good",
      },
      note: "10:30-22:00",
    },
    {
      facility: "宣陵・靖陵",
      states: {
        mon: "closed",
        tue: "good",
        wed: "good",
        thu: "good",
        fri: "good",
        sat: "good",
        sun: "good",
      },
    },
  ],
  stops: [
    {
      time: "11:00",
      nameJa: "狎鴎亭ロデオ通り",
      nameKo: "압구정 로데오거리",
      blurb: "ハイブランドの旗艦店と個性派セレクトショップが混じり合う通り。",
      naverMapUrl: "https://map.naver.com/p/search/압구정 로데오거리",
    },
    {
      time: "12:00",
      nameJa: "ザ・ギワ（昼食）",
      nameKo: "더 기와",
      blurb:
        "瓦屋根モチーフのモダン韓食店。タブレット注文でマッコリの種類も豊富。",
      walkFromPrev: "徒歩5分",
      naverMapUrl: "https://map.naver.com/p/search/더 기와 압구정",
    },
    {
      time: "13:30",
      nameJa: "コゼット島山",
      nameKo: "꽃술 도산",
      blurb: "薬菓が名物のカフェ。平日は12:00開店。",
      hours: "平日12:00〜",
      walkFromPrev: "徒歩10分",
      naverMapUrl: "https://map.naver.com/p/search/꽃술 도산",
    },
    {
      time: "14:30",
      nameJa: "ハウス島山",
      nameKo: "하우스 도산",
      blurb:
        "ジェントルモンスター / タンバリンズ / ヌデイクが1つの建物に。写真映え優先の空間。",
      walkFromPrev: "徒歩5分",
      naverMapUrl: "https://map.naver.com/p/search/하우스 도산",
    },
    {
      time: "15:40",
      nameJa: "島山公園",
      nameKo: "도산공원",
      blurb: "安昌浩(独立運動家)の墓所と記念館。落ち着いて休める公園。",
      walkFromPrev: "徒歩5分",
      naverMapUrl: "https://map.naver.com/p/search/도산공원",
    },
    {
      time: "17:00",
      nameJa: "奉恩寺",
      nameKo: "봉은사",
      blurb: "COEXの向かいの禅寺。夜のライトアップと大仏がフォトジェニック。",
      hours: "5:00-22:00",
      walkFromPrev: "タクシー15分",
      naverMapUrl: "https://map.naver.com/p/search/봉은사",
    },
    {
      time: "18:15",
      nameJa: "ピョルマダン図書館",
      nameKo: "별마당 도서관",
      blurb: "COEX MALL内の巨大な本棚。深夜まで開いてます。",
      hours: "10:30-22:00",
      walkFromPrev: "徒歩5分",
      naverMapUrl: "https://map.naver.com/p/search/별마당 도서관",
    },
  ],
  extras: [
    {
      time: "予備",
      nameJa: "SMTOWN COEX Artium",
      nameKo: "SMTOWN COEX",
      blurb: "K-POP好きなら。カフェ・グッズショップ併設。",
      naverMapUrl: "https://map.naver.com/p/search/SMTOWN COEX",
    },
    {
      time: "予備",
      nameJa: "宣陵・靖陵",
      nameKo: "선릉·정릉",
      blurb: "オフィス街の中の朝鮮王朝の陵。散歩コースに。月曜休み。",
      naverMapUrl: "https://map.naver.com/p/search/선릉 정릉",
    },
  ],
  pitfalls: [
    {
      severity: "info",
      title: "江南は「ひとつの街」ではない",
      body: "江南駅 / 狎鴎亭・島山 / 三成COEX は徒歩でつながりません。地下鉄またはタクシー移動前提で組んでください。",
    },
    {
      severity: "warn",
      title: "カロスキルは空室率43.9%",
      body: "2024年の調査でソウル主要商圏で最高の空室率。日本語ガイドはまだカロスキルを1番に紹介しがちですが、今は狎鴎亭ロデオ・島山公園側に人の流れが移っています。",
    },
    {
      severity: "info",
      title: "江南駅周辺は観光目的なら薄い",
      body: "オフィス街と塾街が中心。買い物・カフェ目当てなら狎鴎亭ロデオ駅で降りるほうが効率的です。",
    },
  ],
  updatedAt: "2026-08-13",
};
