import type { Area } from "@/content/types";

export const hannam: Area = {
  slug: "hannam",
  nameJa: "漢南",
  nameKo: "한남",
  reading: "ハンナム",
  tagline: "聖水は人が多すぎる、と思ったら",
  intro:
    "ギャラリーとカフェとショップが徒歩圏にぎゅっと。人に押されずに歩けるのがいちばんの魅力かも。坂が多いので、ヒールはやめておいたほうが安全です。",
  keyColor: "orchid",
  station: {
    line: "地下鉄6号線",
    name: "漢江鎮駅",
    exit: "1番出口",
  },
  goodFor: [
    "聖水の人混みに疲れた人",
    "ギャラリー・アート好き",
    "落ち着いた大人のカフェ巡りをしたい人",
  ],
  notFor: [
    "伝統的な韓国料理が目当ての人（このエリアはほぼありません）",
    "月曜と日曜しか動けない人",
    "歩きにくい靴（ヒール・厚底）で来る予定の人",
  ],
  weekday: {
    mon: "closed",
    tue: "partial",
    wed: "good",
    thu: "good",
    fri: "good",
    sat: "good",
    sun: "partial",
  },
  weekdayNote:
    "漢南エリアはリウム美術館とペースギャラリーが月曜休館、ペースギャラリーはさらに日曜も休みとなるため、ギャラリー巡り目的なら水曜〜土曜が最適です。ショップとカフェだけなら月曜・日曜も動きます。",
  weekdayTable: [
    {
      facility: "リウム美術館",
      states: {
        mon: "closed",
        tue: "good",
        wed: "good",
        thu: "good",
        fri: "good",
        sat: "good",
        sun: "good",
      },
      note: "要事前予約",
    },
    {
      facility: "ペースギャラリー",
      states: {
        mon: "closed",
        tue: "good",
        wed: "good",
        thu: "good",
        fri: "good",
        sat: "good",
        sun: "closed",
      },
    },
    {
      facility: "タデウス・ロパック",
      states: {
        mon: "closed",
        tue: "partial",
        wed: "partial",
        thu: "partial",
        fri: "partial",
        sat: "partial",
        sun: "closed",
      },
      note: "展示期間中のみ・要確認",
    },
    {
      facility: "ロギ漢南（ディナー）",
      states: {
        mon: "closed",
        tue: "closed",
        wed: "good",
        thu: "good",
        fri: "good",
        sat: "good",
        sun: "good",
      },
    },
    {
      facility: "ショップ・カフェ全般",
      states: {
        mon: "good",
        tue: "good",
        wed: "good",
        thu: "good",
        fri: "good",
        sat: "good",
        sun: "good",
      },
    },
  ],
  stops: [
    {
      time: "10:00",
      nameJa: "リウム美術館",
      nameKo: "리움미술관",
      blurb:
        "サムスンの私設美術館。古美術館・現代美術館・企画展の3棟構成。要事前予約。",
      hours: "10:00-18:00 / 月曜休み",
      reservation: "required",
      tips: [
        "デジタルガイドを借りるとき身分証(パスポート)を預けます",
        "駅から坂を10分登ります",
      ],
      naverMapUrl: "https://map.naver.com/p/search/리움미술관",
      placeType: "Museum",
      address: "ソウル特別市龍山区梨泰院路55キル60-16",
      geo: { latitude: 37.5384, longitude: 126.9990 },
      structuredHours: [
        {
          dayOfWeek: ["tue", "wed", "thu", "fri", "sat", "sun"],
          opens: "10:00",
          closes: "18:00",
        },
      ],
      specialClosedDays: ["mon"],
    },
    {
      time: "12:15",
      nameJa: "イタルリ グクシ 漢南",
      nameKo: "이탈리 국시 한남",
      blurb: "韓×伊フュージョンのうどん屋。行列することが多いです。",
      walkFromPrev: "徒歩10分",
      naverMapUrl: "https://map.naver.com/p/search/이탈리 국시 한남",
    },
    {
      time: "13:45",
      nameJa: "ペースギャラリー ソウル",
      nameKo: "페이스갤러리 서울",
      blurb: "NYの有名ギャラリーの韓国支店。企画は無料で見られます。",
      hours: "10:00-18:00 / 月・日休み",
      fee: "無料",
      walkFromPrev: "徒歩10分",
      naverMapUrl: "https://map.naver.com/p/search/페이스갤러리",
      placeType: "Museum",
      address: "ソウル特別市龍山区梨泰院路262",
      geo: { latitude: 37.5359, longitude: 127.0025 },
      structuredHours: [
        {
          dayOfWeek: ["tue", "wed", "thu", "fri", "sat"],
          opens: "10:00",
          closes: "18:00",
        },
      ],
      specialClosedDays: ["mon", "sun"],
    },
    {
      time: "14:45",
      nameJa: "タデウス・ロパック ソウル",
      nameKo: "타데우스 로팍 서울",
      blurb:
        "オーストリア発の現代美術ギャラリー。展示替えの間は閉まるので事前確認を。",
      walkFromPrev: "徒歩15分",
      naverMapUrl: "https://map.naver.com/p/search/타데우스 로팍",
    },
    {
      time: "16:00",
      nameJa: "ブルーボトル 漢南",
      nameKo: "블루보틀 한남",
      blurb: "コンクリートむき出しの店舗。2階の窓際が人気。",
      walkFromPrev: "徒歩10分",
      naverMapUrl: "https://map.naver.com/p/search/블루보틀 한남",
    },
    {
      time: "17:00",
      nameJa: "マルディメクルディ 漢南",
      nameKo: "마르디 메크르디 한남",
      blurb: "花のロゴでおなじみ。19時閉店なので、この時間帯に。",
      hours: "12:00-19:00",
      walkFromPrev: "徒歩5分",
      naverMapUrl: "https://map.naver.com/p/search/마르디 메크르디",
    },
    {
      time: "18:30",
      nameJa: "ロギ 漢南",
      nameKo: "로기 한남",
      blurb: "モダン韓食のディナー。要予約(1〜2週間前)。",
      reservation: "required",
      walkFromPrev: "徒歩5分",
      naverMapUrl: "https://map.naver.com/p/search/로기 한남",
    },
  ],
  extras: [
    {
      time: "予備",
      nameJa: "サウンドウェーブ 漢南",
      nameKo: "사운즈 한남",
      blurb: "複合施設。書店・カフェ・レストランがまとまっています。",
      naverMapUrl: "https://map.naver.com/p/search/사운즈 한남",
    },
    {
      time: "予備",
      nameJa: "SORAI",
      nameKo: "SORAI",
      blurb: "日本の食材と器のセレクトショップ。日本人には落ち着く空間。",
      naverMapUrl: "https://map.naver.com/p/search/SORAI 한남",
    },
  ],
  pitfalls: [
    {
      severity: "danger",
      title:
        "漢南のギャラリー巡りは月曜休館、ペースギャラリーは日曜も休み",
      body: "リウム美術館とペースギャラリーは月曜休館。ペースギャラリーはさらに日曜も休みなので、漢南のギャラリー巡り目的なら水曜〜土曜が最適です。日曜はカフェとショップだけ動くイメージになります。",
    },
    {
      severity: "warn",
      title: "坂道が多い。ヒール不可",
      body: "漢江鎮駅からリウムまで坂を10分登ります。歩きやすい靴で来てください。",
    },
    {
      severity: "info",
      title: "伝統的な韓国料理はほぼありません",
      body: "漢南はモダン韓食・フュージョン・洋食が中心。サムギョプサル目当てなら他エリアが向いています。",
    },
    {
      severity: "info",
      title: "リウムのガイドは身分証を預けます",
      body: "デジタルガイド(音声解説)の貸出時にパスポート等の身分証が必要。パスポートを預けるのが不安なら、他の身分証もあると安心です。",
    },
  ],
  updatedAt: "2026-08-13",
};
